server {
    listen 80;
    server_name truthfulness.center www.truthfulness.center;
    root /home/shuddhlaxmi/static-sites/truthfulness.center;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
